---
- name: Déploiement Apache
  hosts: web
  become: yes
  tasks:
    - name: Installer Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copier les fichiers
      copy:
        src: ./app/
        dest: /var/www/html/
