---
- name: Déploiement Apache + site
  hosts: web
  become: yes

  tasks:
    - name: Installer Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Copier le contenu de app/
      copy:
        src: ./app/
        dest: /var/www/html/
